#!/usr/bin/env bash

# *********************************** #
#                                     #
# Auto Package Generator              #
#                                     #
# for more information see README.rst #
# *********************************** #
set -e

SCRIPTS_DIR=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )

cd $SCRIPTS_DIR/../

rm -rf generated/thor.odinson

echo "Create new package: 'thor.odinson' in folder ./generated"
bin/create -n --config ./scripts/autogenerate_package.ini -O generated
